import type { UtilityDefinition } from '@/types';

export const UTILITY_REGISTRY: UtilityDefinition[] = [
  {
    id: 'calculator',
    title: 'Calculator',
    description: 'Basic arithmetic operations',
    icon: 'calculator',
    iconFamily: 'Ionicons',
    route: '/utility/calculator',
    category: 'math',
    color: '#E2561E',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  {
    id: 'scientificCalculator',
    title: 'Scientific',
    description: 'Advanced math functions',
    icon: 'function-variant',
    iconFamily: 'MaterialCommunityIcons',
    route: '/utility/scientific-calculator',
    category: 'math',
    color: '#6B4A6E',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  {
    id: 'unitConverter',
    title: 'Unit Converter',
    description: 'Convert length, weight, temp & more',
    icon: 'swap-horizontal',
    iconFamily: 'Ionicons',
    route: '/utility/unit-converter',
    category: 'converter',
    color: '#2E6A66',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'currencyConverter',
    title: 'Currency',
    description: 'Real-time currency conversion',
    icon: 'currency-exchange',
    iconFamily: 'MaterialIcons',
    route: '/utility/currency-converter',
    category: 'finance',
    color: '#4C6B3C',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'emi',
    title: 'EMI Calc',
    description: 'Loan EMI calculator',
    icon: 'bank-outline',
    iconFamily: 'MaterialCommunityIcons',
    route: '/utility/emi-calculator',
    category: 'finance',
    color: '#C2902B',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'gst',
    title: 'GST Calc',
    description: 'GST calculation tool',
    icon: 'receipt',
    iconFamily: 'MaterialCommunityIcons',
    route: '/utility/gst-calculator',
    category: 'finance',
    color: '#B4441C',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'qrScanner',
    title: 'QR Scanner',
    description: 'Scan QR codes & barcodes',
    icon: 'qr-code',
    iconFamily: 'Ionicons',
    route: '/utility/qr-scanner',
    category: 'tools',
    color: '#27566B',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  // {
  //   id: 'notes',
  //   title: 'Notes',
  //   description: 'Quick notes & memos',
  //   icon: 'document-text',
  //   iconFamily: 'Ionicons',
  //   route: '/utility/notes',
  //   category: 'productivity',
  //   color: '#F43F5E',
  //   supportsPersistence: true,
  //   supportsHistory: false,
  //   supportsFavourite: true,
  // },
  {
    id: 'pomodoro',
    title: 'Pomodoro',
    description: 'Focus timer with breaks',
    icon: 'timer',
    iconFamily: 'MaterialCommunityIcons',
    route: '/utility/pomodoro',
    category: 'productivity',
    color: '#7A3246',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  {
    id: 'stopwatch',
    title: 'Stopwatch',
    description: 'Precise time tracking',
    icon: 'stopwatch',
    iconFamily: 'Ionicons',
    route: '/utility/stopwatch',
    category: 'time',
    color: '#4C6B3C',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  {
    id: 'worldClock',
    title: 'World Clock',
    description: 'Time across timezones',
    icon: 'earth',
    iconFamily: 'Ionicons',
    route: '/utility/world-clock',
    category: 'time',
    color: '#3C5A7D',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'passwordGenerator',
    title: 'Password Gen',
    description: 'Secure password generator',
    icon: 'shield-checkmark',
    iconFamily: 'Ionicons',
    route: '/utility/password-generator',
    category: 'tools',
    color: '#6E7A33',
    supportsPersistence: true,
    supportsHistory: true,
    supportsFavourite: true,
  },
  // {
  //   id: 'textUtility',
  //   title: 'Text Tools',
  //   description: 'Transform & analyze text',
  //   icon: 'text',
  //   iconFamily: 'Ionicons',
  //   route: '/utility/text-utility',
  //   category: 'tools',
  //   color: '#D946EF',
  //   supportsPersistence: true,
  //   supportsHistory: false,
  //   supportsFavourite: true,
  // },
  {
    id: 'ageCalculator',
    title: 'Age Calc',
    description: 'Calculate exact age',
    icon: 'calendar',
    iconFamily: 'Ionicons',
    route: '/utility/age-calculator',
    category: 'math',
    color: '#27566B',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'discountCalculator',
    title: 'Discount',
    description: 'Calculate discounts & savings',
    icon: 'pricetag',
    iconFamily: 'Ionicons',
    route: '/utility/discount-calculator',
    category: 'finance',
    color: '#6E7A33',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'counter',
    title: 'Counter',
    description: 'Multi-counter tracker',
    icon: 'add-circle',
    iconFamily: 'Ionicons',
    route: '/utility/counter',
    category: 'tools',
    color: '#C2902B',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
  id: 'compass',
  title: 'Compass',
  description: 'Heading, cardinal direction, GPS coordinates & altitude',
  icon: 'compass-outline',
  iconFamily: 'Ionicons',
  route: '/utility/compass',
  category: 'tools',
  color: '#2E6A66',
  supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
},
{
  id: 'expense',
  title: 'Expenses',
  description: 'Track spending by category with income & balance overview',
  icon: 'wallet-outline',
  iconFamily: 'Ionicons',
  route: '/utility/expense',
  category: 'finance',
  color: '#3C5A7D',
   supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
},

  {
    id: 'tip',
    title: 'Tip & Split',
    description: 'Calculate tips and split bills with friends',
    icon: 'restaurant-outline',
    iconFamily: 'Ionicons',
    route: '/utility/tip-calculator',
    category: 'finance',
    color: '#B5705A',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'colorPicker',
    title: 'Color Picker',
    description: 'Pick colors, build palettes, copy HEX/RGB/HSL',
    icon: 'color-palette-outline',
    iconFamily: 'Ionicons',
    route: '/utility/color-picker',
    category: 'tools',
    color: '#6B4A6E',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'sip',
    title: 'SIP',
    description: 'SIP and lumpsum investment return calculator',
    icon: 'trending-up-outline',
    iconFamily: 'Ionicons',
    route: '/utility/sip-calculator',
    category: 'finance',
    color: '#2E6A66',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  },
  {
    id: 'noise',
    title: 'Noise Meter',
    description: 'Measure ambient sound levels in decibels',
    icon: 'mic-outline',
    iconFamily: 'Ionicons',
    route: '/utility/noise-meter',
    category: 'tools',
    color: '#A6392B',
    supportsPersistence: true,
    supportsHistory: false,
    supportsFavourite: true,
  }

];

export const UTILITY_MAP = Object.fromEntries(
  UTILITY_REGISTRY.map((u) => [u.id, u])
) as Record<string, UtilityDefinition>;

export function getUtilityById(id: string): UtilityDefinition | undefined {
  return UTILITY_MAP[id];
}

export function searchUtilities(query: string): UtilityDefinition[] {
  if (!query.trim()) return UTILITY_REGISTRY;
  const q = query.toLowerCase();
  return UTILITY_REGISTRY.filter(
    (u) =>
      u.title.toLowerCase().includes(q) ||
      u.description.toLowerCase().includes(q) ||
      u.category.toLowerCase().includes(q)
  );
}
